dist: trusty
sudo: required
language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
before_install:
    - wget -O stunnel.tar.gz ftp://ftp.stunnel.org/stunnel/archive/5.x/stunnel-5.29.tar.gz
    - tar -xvzf stunnel.tar.gz
    - cd ./stunnel-5.29 && ./configure && make && sudo make install && cd ..
install:
  - make travis-install
script: TEST="\!ModuleTest" make test
cache:
  directories:
    - $HOME/.m2
addons:
  hostname: jedis
